### ISSUE TITLE
Trivial: iDiscounts: Web Admin: it's necessary mask for "Телефон" field

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#59]
**Steps to reproduce**:
1. Open form of adding and form of editing benefit.

**Actual result**:
There aren't mask for inputting phone number, it's worth to make it so as to have uniform standard of inputting.

**Screenshots**
![image](https://user-images.githubusercontent.com/48205218/54339087-dc583700-4644-11e9-82de-9c725f76cd5c.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
It has become disable, but still presents in the field
**Screenshot**:
![image](https://user-images.githubusercontent.com/48205218/54357147-7385b480-466e-11e9-8ae3-3e02ed095cbc.png)

**Comment by Alena-Shurakova** [comment]
It's better to add mask like 
![image](https://user-images.githubusercontent.com/48205218/54363321-c87bf780-467b-11e9-824d-ce0030b47b05.png)

Also mask was added only in adding benefit form, in editing benefit form it stays as it was:
![image](https://user-images.githubusercontent.com/48205218/54363133-573c4480-467b-11e9-94cf-9ecb7d7ebe92.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
