### ISSUE TITLE
Trivial: iDiscounts: Web Admin: Add category: non-function button 

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#60]
**Describe the bug**:
The button doesn't function. 

**Steps to reproduce:**
1. Open application.
2. Click "Добавить категорию" button
3. Input in the appearing field any valid data
4. Click "+" button

**Actual result**:
After clicking "+" button nothing happens.

**Expected result**:
If this button is for adding category, it isn't needed because there is "Добавить" button in the same window.

**Screenshots**:
![image](https://user-images.githubusercontent.com/48205218/54341636-5b506e00-464b-11e9-982b-7051ea36cd80.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
It has become disable, but still presents in the field
**Screenshot**:
![image](https://user-images.githubusercontent.com/48205218/54357208-a039cc00-466e-11e9-8067-13b742c741f5.png)

**Comment by Alena-Shurakova** [comment]
Fixed
