### ISSUE TITLE
Critical: iDiscounts: Web Admin: impossible to add another location

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#64]
**Describe the bug**:
When user in add benefit or edit benefit forms tries to add another location, he can't do this, because the new address isn't been added.

**Steps to reproduce** the behavior in add benefit form:
1. Open application.
2. Click "Добавить бенефит" button.
3. Choose any city, "Минск", for example.
4. In all fields input valid date (except "Адрес", "Долгота","Широта").
5. In the field "Адрес" input any address, for example,"г. Минск, ул. Толстого, 10".
6. Click "Найти координаты по адресу" button.
7. Click "+" button to input another address.
8. In the field "Адрес" input any another address, for example,"г. Минск, ул. Казимировская, 21".
9. Click "Найти координаты по адресу" button.
10. Click "Добавить бенефит" button.
11. Go to the menu with benefits to see added benefit and make sure that it has only one address.

**Actual result**:
It's impossible to add more than on addresses.

**Expected result**:
It is possible to add some addresses.

**Steps to reproduce** the behavior in edit benefit form:
1. Open application.
2. Open any benefit and click on editing button.
3. Click on "Добавить локацию" button.
4.  In the field "Адрес" input any address which differs from existing.
5. Click "Найти координаты по адресу" button.
6. Click "Добавить" button.
7. Click "Обновить" button.
8. Go to the menu with benefits to see edited benefit and make sure that it has only one address(es) which was before editing.

**Actual result**:
It is impossible to add another address to benefit.

**Expected result:**`
It is possible to add another address.

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Still reproduces in add benefit worm
**Video**:
[Discounts admin (1).zip](https://github.com/wldyslw/benefits.bugtracker/files/2991063/Discounts.admin.1.zip)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed
