### ISSUE TITLE
iDiscounts: Add benefit form: additional address is added only after click "+" button

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#65]
When user inputs another address in add benefit form, he has to click "+" so that this address saves.
When user input the first address, he doesn't need to click "+" button, that is why it's better to save all next inputted addresses without clicking "+" button. This button should be only for appearing of field for additional addresses.
**Current version**: 
So as to save both addresses user has to click "+" button, than "Добавить" button.
![image](https://user-images.githubusercontent.com/48205218/54902486-9d4e9f00-4eea-11e9-9b97-f9c1838891ab.png)

**Enhancement**:
So as to save both addresses user has to click  "Добавить" button.
![image](https://user-images.githubusercontent.com/48205218/54902543-c838f300-4eea-11e9-9967-c612b4d183bf.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Still reproduce when user inputs address by clicking on "Найди адрес по координатам" button

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed
